# Generated by Django 4.2.5 on 2023-10-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTiendaInventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='productos',
        ),
    ]
